databases:
  - name: final_capstone_project
    databaseName: final_capstone_project
    user: final_capstone_project

services:
  - type: web
    name: final_capstone_project
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: final_capstone_project
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false